# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "storeapp"
client_id = "342f1b1625f1feb99a7b44d70d548366"
application_url = "https://specifics-nutrition-stanley-colours.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://specifics-nutrition-stanley-colours.trycloudflare.com/auth/callback",
  "https://specifics-nutrition-stanley-colours.trycloudflare.com/auth/shopify/callback",
  "https://specifics-nutrition-stanley-colours.trycloudflare.com/api/auth/callback",
  "https://specifics-nutrition-stanley-colours.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storeapp4514.myshopify.com"
