# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "storeapp"
client_id = "342f1b1625f1feb99a7b44d70d548366"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
